### ISSUE TITLE
System.DllNotFoundException: 'Microsoft Visual C++ 2017-2019 Redistributable (x64)'

### ISSUE THREAD

**Issue by pmengal** [AlturosDestinations/Alturos.Yolo#122]
I get this exception when I try to use the nuget package in my own project. However, if I run the test GUI, everything run just fine. I also tried to reference the project directly and it ran correctly as well.

**Comment by actopozipc** [comment]
On which platform (Any CPU, x64, x86) do you compile / debug?

**Comment by KoreanPro** [comment]
Hi. I had exactly same problem.

The reason that i found why is because the recent Microsoft Visual C++ 2017 - 2019 has the different name coded in YoloWrapper.cs where it finds the name from the registry(Microsoft Visual C++ 2015 - 2019) .

So if you followed the instruction in read.me, you will be fine with everything except
"Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" in system Requirement part.

I think the main developer of the project is working on it, (thanks for the nice works) but before that i will share the Microsoft Visual C++ Redistributable file first so some people want to check the project result first.

[vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4508703/vcredist_x64.zip)

What you have to do is
1.  if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.

2. Download vcredist_x64.zip that I have uploaded above and unzip it.

3. Install the file and test the project program.

If the problem is solved good for you. If not it would be other problem.

I set two pc and started from installing Win10 to start the project code. Everything worked fine.

win 10 pro / cuda 10.2 / cudnn 7.6.5 / alturos 2.6.4 / x64 debug

win 10 pro / cuda 10.1 / cudnn 7.6.3 / alturos 2.6.2 / x64 debug

Two versions were ok.

I think there are many people having same issue. So I am sharing.

Thank you and sorry for my bad english. (Hope you can understand : D  ) 

And again I would like to thank the developers of this project for their hard works.

**Comment by actopozipc** [comment]
It doesnt solve the problem for me, Ive got alturos 3.0.6 in VS 2019.

**Comment by KoreanPro** [comment]
My recommanded solution may not work on the recent alturos version(3 ~ 3.0.6).

Currently from the nuget package in Visual studio, the recent alturos I can get is version 2.6.4.

If those who can't find 3.0.6 you can download it from 

https://www.nuget.org/packages/Alturos.Yolo/3.0.6-alpha

here.

![image](https://user-images.githubusercontent.com/22042006/80551467-8a1bd600-89fe-11ea-96c3-147fa8618b8c.png)

See if the problem is solved.(The recent alturos version needs recent CUDA and CUDnn)

**Comment by IharrYeuseenka** [comment]
I followed this but anyway I have new one error - "Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

**Comment by massaynus** [comment]
It worked for me... thanks

**Comment by KoreanPro** [comment]
@IharrYeuseenka  Hello~ Did you solved the problem or any updates? What is your operating system, Cuda version, Cudnn version. I am not sure I can solve the problem but I will try to solve your problem.

OS : 
Cuda Version : 
Cudnn Version :

**Comment by dev-ptdi** [comment]
I m facing the same problem, 

Win 10 (will deploy on CentOS 7)
Net Core 3.1
Cuda 11.0

Please help

**Comment by KoreanPro** [comment]
@dev-ptdi HI~ Is there reason why you are using cuda 11.0?(maybe running other program on cuda 11.0)

If that is not the reason, let's start from below version. Contact me afterward please

cuda 10.2 / cudnn 7.6.5 / alturos 2.6.4

**Comment by dev-ptdi** [comment]
because the link always brings me to Cuda 11 and I did not find Cuda 10 there

**Comment by KoreanPro** [comment]
ok try below links~

cuda 10.2  :          https://developer.nvidia.com/cuda-10.2-download-archive
cudnn 7.6.5 :          https://developer.nvidia.com/rdp/cudnn-download
alturos 2.6.4 :      You can find it in Nuget on your Visual Studio

you will need to log in for cudnn. 

![image](https://user-images.githubusercontent.com/22042006/84625176-b55e7400-af1d-11ea-9fef-1b3d02e49a0e.png)

see if these works for you.

**Comment by dev-ptdi** [comment]
Ok.. I am download it ..
btw, does it support Net Core 3.1? .. or did I miss something?

![Capture](https://user-images.githubusercontent.com/62099183/84626275-00bd5600-af0f-11ea-9aa2-7dbb6ebfe462.JPG)

**Comment by KoreanPro** [comment]
Sorry never tried Net Core yet.

At the moment I use .net Framework.
Hope you can figure it out and succeed on the project.

**Comment by dev-ptdi** [comment]
Ok, I have downloaded cuda 10.2, cudnn 7.6.5 and I copy cudnn64_7.dll in /bin folder

the problem still occurs :( .. I suspect this is because Net Core? .. since this is unconfirm to run on Net Core 3.1

![Untitled](https://user-images.githubusercontent.com/62099183/84627890-e6d14280-af11-11ea-90b2-6ef5b4d2bbdb.png)

![Capture](https://user-images.githubusercontent.com/62099183/84627994-11230000-af12-11ea-8304-defbbc916415.JPG)

**Comment by KoreanPro** [comment]
You can see Microsoft Visual C++ **2015-2019** Redistributable in your second image, while in your first image it finds Microsoft Visual C++ **2017-2019** Redistributable.

So uninstall Microsoft Visual C++ **2015-2019** Redistributable first.

then download this zip file, unzip it and install.

Tell me what happens next.

[vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4778783/vcredist_x64.zip)

**Comment by dev-ptdi** [comment]
Hi,

mine is: 14.26.28720
and suggested is 14.22.27821

mine is newest!, I confirm this only run on vcredist 14.22.27821

thanks

**Comment by KoreanPro** [comment]
Yes. Yours is newest.

Alturos version 2.6.x requires old vcredist.

You can use newest vcredist version on Alturos version 3.  .

:-D good luck and have a good day.

**Comment by dev-ptdi** [comment]
Now, I deployed it on CentOS 7..  does it support cross platform?
why it uses Microsoft.Win32.Registry?

Object.DetectAsync: System.TypeInitializationException: The type initializer for 'Microsoft.Win32.Registry' threw an exception.
 ---> System.PlatformNotSupportedException: Registry is not supported on this platform.
   at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)
   at Microsoft.Win32.Registry..cctor()
   --- End of inner exception stack trace ---
   at Alturos.Yolo.YoloWrapper.IsMicrosoftVisualCPlusPlus2017Available()
   at Alturos.Yolo.YoloWrapper.GetEnvironmentReport()
   at Alturos.Yolo.YoloWrapper.Initialize(String configurationFilename, String weightsFilename, String namesFilename, Int32 gpu, Boolean ignoreGpu, Boolean ignoreCPlusPlusDetection)
   at Alturos.Yolo.YoloWrapper..ctor(YoloConfiguration yoloConfiguration, Boolean ignoreGpu)
   at PrimeAI.Models.Object.DetectAsync(Byte[] _bytes) in D:\Project\PTDigital\PrimeAI\Models\Object.cs:line 32

**Comment by KoreanPro** [comment]
Oh this project will not work in linux. The purpose of this project is to run yolo on C# in windows. In the discription on the project, it says "In the background we are use the Windows Yolo version of AlexeyAB/darknet."

If you want to run in centos or linux. Why not use AlexeyAB/darknet?

Alturos is C# package for windows.

**Comment by PHHUANG1970** [comment]
The Alturos.Yolo v2.6.x was run well before in my PC. However, I installed "Cuda 11.0" "cudnn v7.6.4" and "2015-2019 C++ redistributable" yesterday, and the project can't run then.  The error is-- Alturos.Yolo.YoloInitializeException: 'Microsoft Visual C++ 2017-2019 Redistributable (x64)' .  
Can anybody help me to fix it?

**Comment by KoreanPro** [comment]
Hello @PHHUANG1970 

Sorry for late reply. I was a bit busy..

I think the problem is your C++ redistributable is the recent one. 

Alturos v2.6.x requires old redistributable.

Here is one for you.

[vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4910168/vcredist_x64.zip)

What you have to do is

1. if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.

2. Download vcredist_x64.zip that I have uploaded above and unzip it.

3. Install the file and test the project program.

If it didn't help let me know.

**Comment by PHHUANG1970** [comment]
> Hello @PHHUANG1970
> 
> Sorry for late reply. I was a bit busy..
> 
> I think the problem is your C++ redistributable is the recent one.
> 
> Alturos v2.6.x requires old redistributable.
> 
> Here is one for you.
> 
> [vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4910168/vcredist_x64.zip)
> 
> What you have to do is
> 
> 1. if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.
> 2. Download vcredist_x64.zip that I have uploaded above and unzip it.
> 3. Install the file and test the project program.
> 
> If it didn't help let me know.

**Comment by PHHUANG1970** [comment]
@KoreanPro      I have fixed my problem using the old version of  vcredist_x64.zip.   Thank you for your help.

**Comment by Tyler871203** [comment]
> Hi. I had exactly same problem.
> 
> The reason that i found why is because the recent Microsoft Visual C++ 2017 - 2019 has the different name coded in YoloWrapper.cs where it finds the name from the registry(Microsoft Visual C++ 2015 - 2019) .
> 
> So if you followed the instruction in read.me, you will be fine with everything except
> "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" in system Requirement part.
> 
> I think the main developer of the project is working on it, (thanks for the nice works) but before that i will share the Microsoft Visual C++ Redistributable file first so some people want to check the project result first.
> 
> [vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4508703/vcredist_x64.zip)
> 
> What you have to do is
> 
> 1. if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.
> 2. Download vcredist_x64.zip that I have uploaded above and unzip it.
> 3. Install the file and test the project program.
> 
> If the problem is solved good for you. If not it would be other problem.
> 
> I set two pc and started from installing Win10 to start the project code. Everything worked fine.
> 
> win 10 pro / cuda 10.2 / cudnn 7.6.5 / alturos 2.6.4 / x64 debug
> 
> win 10 pro / cuda 10.1 / cudnn 7.6.3 / alturos 2.6.2 / x64 debug
> 
> Two versions were ok.
> 
> I think there are many people having same issue. So I am sharing.
> 
> Thank you and sorry for my bad english. (Hope you can understand : D )
> 
> And again I would like to thank the developers of this project for their hard works.

However, when I use this in the unity project it didn't go well.
(I have installed the new redistributable one and I can run Alturos on .NET core.)

**Comment by Kirill-Sakov** [comment]
> Hi. I had exactly same problem.
> 
> The reason that i found why is because the recent Microsoft Visual C++ 2017 - 2019 has the different name coded in YoloWrapper.cs where it finds the name from the registry(Microsoft Visual C++ 2015 - 2019) .
> 
> So if you followed the instruction in read.me, you will be fine with everything except
> "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" in system Requirement part.
> 
> I think the main developer of the project is working on it, (thanks for the nice works) but before that i will share the Microsoft Visual C++ Redistributable file first so some people want to check the project result first.
> 
> [vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4508703/vcredist_x64.zip)
> 
> What you have to do is
> 
> 1. if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.
> 2. Download vcredist_x64.zip that I have uploaded above and unzip it.
> 3. Install the file and test the project program.

My problem is solved, thank you!

**Comment by DarrenWray** [comment]
For those of you who need to fix this in v2.x without installing a back version of the vcredist_x64.zip file provided by @KoreanPro, adding the details of the latest vcredist release number to the **IsMicrosoftVisualCPlusPlus2017Available** method in **DefaultYoloSystemValidator.cs** will solve the issue. 

As of Feb 5th 2021, the redist is V14.28. You can find this by using Regedit and finding Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle.

or similar for the version you have installed.

If you add 
{ @"Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle", "Microsoft Visual C++ 2015-2019 Redistributable (x64)" }

to the end of the dictionary of VC releases, as below, it should overcome the exception:

![image](https://user-images.githubusercontent.com/25084700/107079008-1efdfc00-67e7-11eb-98df-e5bd8a626695.png)

I hope this helps others trying to resolve the issue.

**Comment by M2V2** [comment]
Hi, I'm having this problem:
![WhatsApp Image 2021-02-24 at 15 00 50](https://user-images.githubusercontent.com/13024625/109048024-4f81d900-76b5-11eb-84a6-8f6be6b00e2e.jpeg)

I've already tried the solution of korean pro about the Microsoft Visual C++ 2015-2019 but it didn't work for me. I also added { @"Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle", "Microsoft Visual C++ 2015-2019 Redistributable (x64)" } into checkKeys but nothing.

Anyone can help me ? I'm working on a i7 7th gen pc without graphic card (8GB ram)

**Comment by DarrenWray** [comment]
> Hi, I'm having this problem:
> ![WhatsApp Image 2021-02-24 at 15 00 50](https://user-images.githubusercontent.com/13024625/109048024-4f81d900-76b5-11eb-84a6-8f6be6b00e2e.jpeg)
> 
> I've already tried the solution of korean pro about the Microsoft Visual C++ 2015-2019 but it didn't work for me. I also added { @"Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle", "Microsoft Visual C++ 2015-2019 Redistributable (x64)" } into checkKeys but nothing.
> 
> Anyone can help me ? I'm working on a i7 7th gen pc without graphic card (8GB ram)

Did you try looking in your registry (using Regedit) for the entry: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle.

That will give you the name of the bundle name installed on your machine, it should match one of those in the DefaultYoloSystemValidator.cs file.

I hope that helps,

Darren

**Comment by M2V2** [comment]
> > Hi, I'm having this problem:
> > ![WhatsApp Image 2021-02-24 at 15 00 50](https://user-images.githubusercontent.com/13024625/109048024-4f81d900-76b5-11eb-84a6-8f6be6b00e2e.jpeg)
> > I've already tried the solution of korean pro about the Microsoft Visual C++ 2015-2019 but it didn't work for me. I also added { @"Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle", "Microsoft Visual C++ 2015-2019 Redistributable (x64)" } into checkKeys but nothing.
> > Anyone can help me ? I'm working on a i7 7th gen pc without graphic card (8GB ram)
> 
> Did you try looking in your registry (using Regedit) for the entry: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\VC,redist.x64,amd64,14.28,bundle.
> 
> That will give you the name of the bundle name installed on your machine, it should match one of those in the DefaultYoloSystemValidator.cs file.
> 
> I hope that helps,
> 
> Darren


I did it too, but not working, I put a list of bundles including that one that appears in HKEYLocal.
Now I change PC, I will try on a i7 10th gen, 16GB RAM and RTX2070  hope that works!!
I guess it's something about the graphic cards
P.S: I also edited on YoloWrapper.cs all the parts where it enables the gpu I change to use cpu

**Comment by anvarj** [comment]
@KoreanPro Thanks, it only worked after reinstalling   <a href="https://github.com/AlturosDestinations/Alturos.Yolo/files/4508703/vcredist_x64.zip">vcredist_x64.zip</a>

**Comment by Dungiot** [comment]
> Hi. I had exactly same problem.
> 
> The reason that i found why is because the recent Microsoft Visual C++ 2017 - 2019 has the different name coded in YoloWrapper.cs where it finds the name from the registry(Microsoft Visual C++ 2015 - 2019) .
> 
> So if you followed the instruction in read.me, you will be fine with everything except
> "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" in system Requirement part.
> 
> I think the main developer of the project is working on it, (thanks for the nice works) but before that i will share the Microsoft Visual C++ Redistributable file first so some people want to check the project result first.
> 
> [vcredist_x64.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/4508703/vcredist_x64.zip)
> 
> What you have to do is
> 
> 1. if you already downloaded and installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 und 2019 x64" from the instruction, double click the file again and select remove.
> 2. Download vcredist_x64.zip that I have uploaded above and unzip it.
> 3. Install the file and test the project program.
> 
> If the problem is solved good for you. If not it would be other problem.
> 
> I set two pc and started from installing Win10 to start the project code. Everything worked fine.
> 
> win 10 pro / cuda 10.2 / cudnn 7.6.5 / alturos 2.6.4 / x64 debug
> 
> win 10 pro / cuda 10.1 / cudnn 7.6.3 / alturos 2.6.2 / x64 debug
> 
> Two versions were ok.
> 
> I think there are many people having same issue. So I am sharing.
> 
> Thank you and sorry for my bad english. (Hope you can understand : D )
> 
> And again I would like to thank the developers of this project for their hard works.

thanks you!
I have used it!
