### ISSUE TITLE
No Dataset Available Exception

### ISSUE THREAD

**Issue by MaroisConsulting** [AlturosDestinations/Alturos.Yolo#124]
As soon as I start the app I get

Cannot found a valid dataset System.IO.FileNotFoundException: Cannot found pre-trained model, check all config files available (.cfg, .weights, .names)
   at Alturos.Yolo.YoloConfigurationDetector.Detect(String path)
   at Alturos.Yolo.TestUI.Main.Initialize(String path) in C:\Projects\Alturos.Yolo\Alturos.Yolo-master\src\Alturos.Yolo.TestUI\Main.cs:line 255

This message looks like there' some configuration that supposed to happen.

I don't see any form of documentation, so I don't know what "weights" or "names " means. Is there any documenation other than the few lines of code provided ?

**Comment by actopozipc** [comment]
Can you show your bin/Debug directory? It might be that you miss the config files.
Try the following in the packet-manager console:  

> install-package Alturos.YoloV2TinyVocData

**Comment by MaroisConsulting** [comment]
> Can you show your bin/Debug directory? It might be that you miss the config files.
> Try the following in the packet-manager console:
> 
> > install-package Alturos.YoloV2TinyVocData

I did the install. I get the same error.

I looked at the config. files for all 5 projects, There's nothing there except default, empty config files.

**Comment by ngoche** [comment]
In my case, I used:
`var config = configurationDetector.Detect("D:\\YoloTestApp\\bin\\Debug");`
istead
`var config = configurationDetector.Detect();`
And make sure you already copy those files (.cfg, .weights, .names) to Debug(make your own Debug folder if doesn't exist
